<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        //$this->call(UsersTableSeeder::class);
    	$this->call(PermissionTableSeeder::class);
        $this->call(YearsTableSeeder::class);
        $this->call(SeasonsTableSeeder::class);
		$this->call(RacetypeTableSeeder::class);
		$this->call(RacecategoryTableSeeder::class);
		$this->call(RaceconditionsTableSeeder::class);
		$this->call(OwnertypeTableSeeder::class);
		$this->call(HorsesexTableSeeder::class);
		$this->call(HorsenationalityTableSeeder::class);
		$this->call(HorsecolorTableSeeder::class);
		$this->call(HorseequipmentTableSeeder::class);
		$this->call(HorseshoesTableSeeder::class);
		$this->call(HorseloadingTableSeeder::class);
		$this->call(PartytypeTableSeeder::class);
		$this->call(RacingincidentmastersTableSeeder::class);
		$this->call(RacingbantypeTableSeeder::class);
		$this->call(StakesTableSeeder::class);
		$this->call(RacinghorseTableSeeder::class);
		$this->call(RacinghorsegatepassdetailsTableSeeder::class);
		$this->call(RacingpartyregistrationsTableSeeder::class);
		$this->call(RacingpartyaddressTableSeeder::class);
		$this->call(RacingpartybankdetailsTableSeeder::class);
		$this->call(RacingpartydocumentdetailsTableSeeder::class);
		$this->call(CountriesTableSeeder::class);
		$this->call(StatesTableSeeder::class);
		$this->call(CitiesTableSeeder::class);
		$this->call(ClubsTableSeeder::class);
		$this->call(FeetypeTableSeeder::class);
		$this->call(RacingfinesTableSeeder::class);
		$this->call(LicencetypesTableSeeder::class);
		$this->call(SeasondatesTableSeeder::class);
		$this->call(SeasondatesdetailsTableSeeder::class);
		$this->call(ProspectusdatesentryTableSeeder::class);
		$this->call(RacenamesTableSeeder::class);
		$this->call(ProspectusentryTableSeeder::class);
		$this->call(ProspectusentrystakesTableSeeder::class);
		$this->call(ProspectusentryfeeTableSeeder::class);
		$this->call(TrophypresenterTableSeeder::class);
		$this->call(RacinghorsetrainershipdetailsTableSeeder::class);
		$this->call(RacinghorsesaledetailsTableSeeder::class);
		$this->call(RacinghorsesellersTableSeeder::class);
		$this->call(RacinghorsebuyersTableSeeder::class);
		$this->call(RacinghorsecontingencyleasedetailsTableSeeder::class);
		$this->call(RacinghorseownershipdetailsTableSeeder::class);
		$this->call(RacingentriesTableSeeder::class);
		$this->call(RacingdivisionsTableSeeder::class);
		$this->call(RacinghorseratingdetailsTableSeeder::class);
		$this->call(PoolsTableSeeder::class);
		$this->call(MembersTableSeeder::class);
		$this->call(ContentTableSeeder::class);
		$this->call(ratingsWeightTableSeeder::class);
		$this->call(ProspectusBackupTableSeeder::class);
		$this->call(RacingColorTableSeeder::class);
		$this->call(RacingCapColorTableSeeder::class);
		$this->call(RacingTrackColorTableSeeder::class);
		$this->call(RacingAuthorityTableSeeder::class);
		$this->call(RacingTrackAllotmentTableSeeder::class);
		$this->call(RacingSwimmingDetailsTableSeeder::class);
		$this->call(AgentAuthorizationTableSeeder::class);
		$this->call(OutstationOwnersBanEntryTableSeeder::class);
		$this->call(JockeyOutstationWinsTableSeeder::class);
		$this->call(TestTypeTableSeeder::class);
		$this->call(SampleTypeTableSeeder::class);
		$this->call(ParameterTypeTableSeeder::class);
		$this->call(ServiceTypeTableSeeder::class);
		$this->call(LabMasterTableSeeder::class);
		$this->call(ParameterUomTableSeeder::class);
		$this->call(FinancialYearsTableSeeder::class);
		$this->call(CategoriesTableSeeder::class);
		$this->call(SubCategoriesTableSeeder::class);
		$this->call(uomTableSeeder::class);
		$this->call(MaterialsTableSeeder::class);
		$this->call(RacingAccountsBmcBillTableSeeder::class);
		$this->call(RacingAccountsBmcBillDetailsTableSeeder::class);
		$this->call(GlobalSettingsTableSeeder::class);
		$this->call(RacingRaceIncidentsTableSeeder::class);
		$this->call(RacingHorseContingencyLeaseOwnersTableSeeder::class);
		$this->call(RacingTransactionsRacingHorseContingencyLeaseOwnersTableSeeder::class);
		$this->call(RacingHorseContingencyLeaseOwnersTableSeeder::class);
		$this->call(RacingHorseContingencyLeaseOwnersPayTableSeeder::class);
		$this->call(RacingAccountsStakesTableSeeder::class);
		$this->call(RacingAccountsStakesDetailsTableSeeder::class);
		$this->call(RacingAccountsStakesDeductionsTableSeeder::class);
		$this->call(RacingAccountsStakesAmountsTableSeeder::class);
		$this->call(StakesTaxesMTableSeeder::class);
		$this->call(AgentAuthorizationDetailsTableSeeder::class);
		$this->call(TreatmentTypesTableSeeder::class);
		$this->call(PathologicalTestNormsTableSeeder::class);
		$this->call(MedicineChargesTableSeeder::class);
		$this->call(TreatmentTypeMedicineLinkTableSeeder::class);
		$this->call(ServiceChargesTableSeeder::class);
		$this->call(TestTypeSampleLinkTableSeeder::class);
		$this->call(VeterinaryTreatmentTableSeeder::class);
		$this->call(VeterinaryTreatmentDetailsTableSeeder::class);
		$this->call(PurchaseIndentTableSeeder::class);		
    }
}
